# Generated by Django 3.2.7 on 2021-09-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0002_proyecto_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('SI', 'Sin iniciar'), ('EP', 'En proceso'), ('F', 'Finalizado')], default='SI', max_length=2),
        ),
    ]
