# Generated by Django 3.2.7 on 2021-09-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0003_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('SI', 'Sin iniciar'), ('EP', 'En proceso'), ('F', 'Finalizado')], default='SI', max_length=10),
        ),
    ]
